fix an error
Traceback (most recent call last):
  File "D:\miniconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\miniconda\Scripts\virusrecom.exe\__main__.py", line 7, in <module>
  File "D:\miniconda\lib\site-packages\virusrecom\main.py", line 550, in starts
    virus_infor_calculate(parameter_dic,
  File "D:\miniconda\Lib\site-packages\virusrecom\corecp.py", line 81, in virus_infor_calculate
    site_ic_csv_path = wic_calculation(seq_matrix, lineage_name_list,
  File "D:\miniconda\Lib\site-packages\virusrecom\my_func.py", line 271, in wic_calculation
    for (columnName, columnData) in lineage_seq_df.iteritems():
  File "D:\miniconda\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'. Did you mean: 'isetitem'?
AttributeError: 'DataFrame' object has no attribute 'iteritems'. Did you mean: 'isetitem'?
It is because the new version pandas had deleted this attribute, and we can use items to replace it.